### PR TITLE
Fix ability build directly on different target platforms

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Added the ability to build the edge-orchestration directly on different target platforms: i386/i686, aarch64.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

```
Need to run the `./build.sh` script directly on target platform (Ex: i386/i686 or aarch64)
 
 - [x] Execution of Container

```

**Test Configuration**:
* Firmware version: Ubuntu 16.04
* Hardware: x86, aarch64
* Toolchain: Docker and Go recomended versions
* Edge Orchestration Release: Baobab

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
LGTM. Building on Ubuntu and RPi2 is fine.

**Comment by MoonkiHong** [comment]
> LGTM. Building on Ubuntu and RPi2 is fine.

@t25kim Thank you for your passionate contributions to validate this PR. ^^

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
