### PR TITLE
Fix CWE-78

### LINKED ISSUE #298: [Security] CWE-78 Command built from user-controlled sources
CWE-78 security issue is detected by lgtm and CodeQL.
We need a process to check if the input that launches the native app contains a malicious string.

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

After analyzing the existing code, it should be noted that sanitization measures have been made in the edge-orchestration:

1. analysis for a [command injection using an escape sequence](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/internal/common/commandvalidator/injectionchecker/injectionchecker.go)
2. filtering commands that are on the [blacklist](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/internal/common/commandvalidator/blacklist/blacklist.go) 
3. only those commands that are previously described in the configuration file (ex. [ls_srv.conf](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/test/native/ls_srv/ls_srv.conf)) can be executed.

Strengthening against attacks of this kind can be:
1) Using the integrity check and digital signature of the configuration file.
2) Applying  Linux Kernel protection modules.

All attempts to eliminate the security alert by changing the source code were unsuccessful.
The elimination requires hard-coding the string literals of the commands to be used, but this greatly limits the flexibility of the edge-orchestration and doesn't add a significant increase in security.

**Therefore, I propose to mark this alert as a _fall positive_.**

 Fixes #298 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

The result can be seen after merging the PR and restarting the LGTM 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
I agree with your idea. 
Is there anything else we should put some in the [injectionOperators](https://github.com/lf-edge/edge-home-orchestration-go/blob/a37ab879d23f997db2bb1aa41914fd258aae37bc/internal/common/commandvalidator/injectionchecker/injectionchecker.go#L24)?

**Comment by tdrozdovsky** [comment]
> 
> 
> I agree with your idea.
> Is there anything else we should put some in the [injectionOperators](https://github.com/lf-edge/edge-home-orchestration-go/blob/a37ab879d23f997db2bb1aa41914fd258aae37bc/internal/common/commandvalidator/injectionchecker/injectionchecker.go#L24)?
That's enough for the moment! Thank you!

**Review by MoonkiHong — APPROVED** [review]
+1

**Comment by MoonkiHong** [comment]
@suresh-lc PTAL. 😄

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
