### PR TITLE
Add sonarcloud configuration file

### LINKED ISSUE #254: [Static Analysis] Integration of SonarCloud for CII BP Badge process
- Cross reference from @tdrozdovsky: https://github.com/lf-edge/edge-home-orchestration-go/pull/251#discussion_r567477862

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@gmail.com>

# Description

A file is added to configure the SonarCloud analyzer.
I would like to note that the use of this configuration file is not intended for automatic testing and may disable it. 
_If you import a project that already contains a sonar-project.properties file, SonarCloud will deem the project ineligible for automatic analysis. You can still force automatic analysis if you choose_ from official documentation.
**Hence this change is for testing purposes and can be reverted!**

Other configuration properties can be added as needed.   

Fixes #254 

## Type of change

- [x] CI update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tdrozdovsky** [comment]
Should we analyze the `third_party/zeroconf` folder?

**Comment by MoonkiHong** [comment]
> Should we analyze the `third_party/zeroconf` folder?

@tdrozdovsky I personally do not think so, but it depends on our tentative plan to contribute any codes further into `zeroconf` later. We could get an advice from @t25kim as well.

**Comment by t25kim** [comment]
> Should we analyze the `third_party/zeroconf` folder?

I don't think we need to include the `third_party` folder to SonarCloud Analysis.

**Review by t25kim — APPROVED** [review]
LGTM. Thanks!

**Comment by tdrozdovsky** [comment]
> 
> 
> > Should we analyze the `third_party/zeroconf` folder?
> 
> I don't think we need to include the `third_party` folder to SonarCloud Analysis.

I also think that this folder should be excluded. It is currently on.

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Review by suresh-lc — APPROVED** [review]
LGTM

**Comment by tdrozdovsky** [comment]
As discussed earlier, I excluded the `third_party` folder from SonarCloud analysis.

**Review by MoonkiHong — APPROVED** [review]
Copy that. It is for the efficiency of the static analysis from SonarCloud (aligned with other committers as well).

**Comment by t25kim** [comment]
@tdrozdovsky Can you exclude `mocks` folder as well?

**Comment by tdrozdovsky** [comment]
> 
> 
> @tdrozdovsky Can you exclude `mocks` folder as well?

OK, TBD

**Pull request merged**
