### PR TITLE
TxT record parse as in Android

### PR DESCRIPTION
**Pull request by suresh-lc**
# Description

TxT Record parsing needs to be as per mDNS protocol. When we tried to develop for the Android part, the parsing was not happening properly

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Home Edge was executed in Linux device and Home Edge in Android device. The logs were checked for completeness

```
Execution as below
  - [ ] Execution of Container
  - [ ] Execution on top of Android
Android device: 192.168.1.100
Android Device : 192.168.1.105
Linux Device : 192.168.1.109

Run Home Edge as container on Linux device. Following log shows appropriate Txt Record parsing

INFO[2022-07-11T11:28:57Z]roundtriptime.go:92 checkRTT Get "http://192.168.1.100:56002/api/v1/ping": dial tcp 192.168.1.100:56002: connect: connection refused 
INFO[2022-07-11T11:29:01Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:01Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:01Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.100]), RTT(0) 
INFO[2022-07-11T11:29:01Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:01Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:01Z]discovery.go:843 getNetworkDB [discoverymgr] not found error : edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c does not exist 
INFO[2022-07-11T11:29:01Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:01Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:01Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:01Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:01Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:02Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:02Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:02Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:02Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:02Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:02Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:02Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:02Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:02Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:02Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:03Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:03Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:03Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.100]), RTT(0) 
INFO[2022-07-11T11:29:03Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:03Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:05Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:05Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:05Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.100]), RTT(0) 
INFO[2022-07-11T11:29:05Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:05Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:09Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:09Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:09Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.100]), RTT(0) 
INFO[2022-07-11T11:29:09Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:09Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:12Z]discovery.go:871 activeDiscovery [discoverymgr] activeDiscovery!!!            
INFO[2022-07-11T11:29:12Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-07-11T11:29:12Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-07-11T11:29:12Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.109]), RTT(0) 
INFO[2022-07-11T11:29:12Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([DataStorage]) 
INFO[2022-07-11T11:29:12Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:12Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-07-11T11:29:12Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-07-11T11:29:12Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.109]), RTT(0) 
INFO[2022-07-11T11:29:12Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([DataStorage]) 
INFO[2022-07-11T11:29:12Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:17Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-ad32fe39-4639-405f-9af0-b34ef9d5be8c 
INFO[2022-07-11T11:29:17Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:17Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.100]), RTT(0) 
INFO[2022-07-11T11:29:17Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:17Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:18Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:18Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:18Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:18Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:18Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:18Z]discovery.go:843 getNetworkDB [discoverymgr] not found error : edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad does not exist 
INFO[2022-07-11T11:29:18Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:18Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:18Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:18Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:18Z]discovery.go:589 func1                                              

INFO[2022-07-11T11:29:19Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:19Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(), Platform() 
INFO[2022-07-11T11:29:19Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([]), RTT(0) 
INFO[2022-07-11T11:29:19Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:19Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:19Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:19Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:19Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.105]), RTT(0) 
INFO[2022-07-11T11:29:19Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:19Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:20Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:20Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:20Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.105]), RTT(0) 
INFO[2022-07-11T11:29:20Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:20Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:22Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:22Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:22Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.105]), RTT(0) 
INFO[2022-07-11T11:29:22Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:22Z]discovery.go:589 func1                                              
INFO[2022-07-11T11:29:26Z]discovery.go:585 func1 [deviceDetectionRoutine] edge-orchestration-d95fd29e-edf8-4553-9e41-204f27422cad 
INFO[2022-07-11T11:29:26Z]discovery.go:586 func1 [deviceDetectionRoutine] confInfo    : ExecType(android), Platform(android) 
INFO[2022-07-11T11:29:26Z]discovery.go:587 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.105]), RTT(0) 
INFO[2022-07-11T11:29:26Z]discovery.go:588 func1 [deviceDetectionRoutine] serviceInfo : Services([]) 
INFO[2022-07-11T11:29:26Z]discovery.go:589 func1                                              



```

**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64 (e.g., x86, x86-64, arm, arm64)
* Toolchain: Docker v20.10 & Go v1.16
* Edge Orchestration Release: v1.1.x

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
@suresh-lc I recommend you to take a look at [`DoGetOrchestrationInfo`](https://github.com/lf-edge/edge-home-orchestration-go/blob/f506714bcee95009dcbfa61cdb3cc52c44293229/internal/restinterface/client/restclient/restclient.go#L198) and [`convertServiceEntrytoDB`](https://github.com/lf-edge/edge-home-orchestration-go/blob/f506714bcee95009dcbfa61cdb3cc52c44293229/internal/controller/discoverymgr/wrapper/wrapper.go#L165).

**Comment by t25kim** [comment]
The example of Home Edge TXT is `txt = ["DataStorage" "app1" "container" "docker"]`.
What about changing the structure like android? 
It is likely to be `txt = ["Service=DataStorage;app1" "ExecType=container" "Platform=docker"]`.

**Comment by nitu-s-gupta** [comment]
One doubt, The suggestion is to make it similar to saving the data in servicedb i.e.  [convertServiceEntrytoDB](https://github.com/lf-edge/edge-home-orchestration-go/blob/f506714bcee95009dcbfa61cdb3cc52c44293229/internal/controller/discoverymgr/wrapper/wrapper.go#L165). this function or change the way it is displayed in logs https://github.com/lf-edge/edge-home-orchestration-go/blob/f506714bcee95009dcbfa61cdb3cc52c44293229/internal/controller/discoverymgr/discovery.go#L549

**Comment by t25kim** [comment]
The information stored in Platform and ExecType is the same as now and the logs too.
The difference is that we should parse the TXT string to know Platform and ExecType, not static positions such as data.Text[0], data.Text[1]. I think we can get this idea if we revise these [lines](https://github.com/lf-edge/edge-home-orchestration-go/blob/f506714bcee95009dcbfa61cdb3cc52c44293229/internal/controller/discoverymgr/wrapper/wrapper.go#L172L180).

**Comment by t25kim** [comment]
> The current example of Home Edge TXT is `txt = ["DataStorage" "app1" "container" "docker"]`. What about changing the structure like android? It is likely to be `txt = ["DataStorage" "app1" "ExecType=container" "Platform=docker"]`.

I think we can achieve it by modifying the lines below. 
https://github.com/lf-edge/edge-home-orchestration-go/blob/b889663efcd8e7e9fd87734981490e21e48b82cf/internal/controller/discoverymgr/discovery.go#L525L526
https://github.com/lf-edge/edge-home-orchestration-go/blob/b889663efcd8e7e9fd87734981490e21e48b82cf/internal/controller/discoverymgr/discovery.go#L242L243
```
    Text = append(Text, "Platform="+platform)
    Text = append(Text, "ExecType="+executionType)
```

**Review by t25kim — APPROVED** [review]
LGTM! Thanks for the contribution!

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Pull request merged**
