### PR TITLE
[Refactoring] Build Script in terms of TC

### LINKED ISSUE #278: [Refactoring] Build script
How about refactoring `build.sh` file a little bit shorter?
- [x] Remove [`PKG_LIST`](https://github.com/lf-edge/edge-home-orchestration-go/blob/ae413fe2ecb3eb9176d862117b476c7f26431f99/build.sh#L9) and use a relative path to run test scenarios.
- [ ] Streamline code in terms of `BUILD_TAGS` such as `secure`, `mnedc`.
- [ ] Delete duplicated code that can be eliminated

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Refactor `build.sh` file in terms of TC in order to reduce LOC
- Remove PKG_LIST
- Use relative path to run TC
Fixes #278 

## Type of change

- [x] Code cleanup/refactoring
- [x] This change requires a documentation update

# How Has This Been Tested?
Run TC with `./build.sh` file.
- $ ./build.sh test
- $ ./build.sh test ./internal/common/commandvalidator/

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
This is great for improving visibility from the build script. LGTM.

**Review by tdrozdovsky — APPROVED** [review]

**Review by MoonkiHong — APPROVED** [review]
+1! 😄

**Comment by suresh-lc** [comment]
Description can be little more for any third person to understand like why we do the change and how. Understand we are fixing an issue #278 . Later date when we check the PR, better description would be good and we need not to go to issue also.

**Comment by MoonkiHong** [comment]
> Description can be little more for any third person to understand like why we do the change and how. Understand we are fixing an issue #278 . Later date when we check the PR, better description would be good and we need not to go to issue also.

Please see https://github.com/lf-edge/edge-home-orchestration-go/pull/279/commits/65a801da31888b0053500d0d591ac328f5759819. Seems it has an enough description in the commit message. Any issue from you?

**Comment by t25kim** [comment]
> Description can be little more for any third person to understand like why we do the change and how. Understand we are fixing an issue #278 . Later date when we check the PR, better description would be good and we need not to go to issue also.

Thank you for the review!
I will write PR description more specifically from next time!

**Comment by suresh-lc** [comment]
> > Description can be little more for any third person to understand like why we do the change and how. Understand we are fixing an issue #278 . Later date when we check the PR, better description would be good and we need not to go to issue also.
> 
> Please see [65a801d](https://github.com/lf-edge/edge-home-orchestration-go/commit/65a801da31888b0053500d0d591ac328f5759819). Seems it has an enough description in the commit message. Any issue from you?

Had checked the message. Why removal of PKG_LST can be little more explained is what I wanted to say. Was following : "We explain our solution and why we are doing what we are doing, as opposed to describing what we are doing."

**Comment by MoonkiHong** [comment]
> Why removal of PKG_LST can be little more explained is what I wanted to say.

@suresh-lc It is well explained with the linked issue #278. Plus there is a description why need this commit (reduce of LoC). In addition to that, I would like to recommend you to also provide your rectified recommendation if you truly want an improved revision from contributors, otherwise, the discussion will go to a lot of chats and overheads.

**Comment by suresh-lc** [comment]
> > Why removal of PKG_LST can be little more explained is what I wanted to say.
> 
> @suresh-lc It is well explained with the linked issue #278. Plus there is a description why need this commit (reduce of LoC). In addition to that, I would like to recommend you to also provide your rectified recommendation if you truly want an improved revision from contributors, otherwise, the discussion will go to a lot of chats and overheads.

@MoonkiHong : thanks for your comments. Ya had mentioned that we are resolving the issue #278 . Since wanted to improve the contributions , had given the comment and not to just have chats, guess my intention was not rightly conveyed, sorry for that.

**Comment by suresh-lc** [comment]
> > > Why removal of PKG_LST can be little more explained is what I wanted to say.
> > 
> > 
> > @suresh-lc It is well explained with the linked issue #278. Plus there is a description why need this commit (reduce of LoC). In addition to that, I would like to recommend you to also provide your rectified recommendation if you truly want an improved revision from contributors, otherwise, the discussion will go to a lot of chats and overheads.
> 
> @MoonkiHong : thanks for your comments. Ya had mentioned that we are resolving the issue #278 . Since wanted to improve the contributions , had given the comment and not to just have chats, guess my intention was not rightly conveyed, sorry for that.

The "reduce of LoC" has been added and it looks fine now.  This gives why we are doing the change and hence it looks better.

**Review by suresh-lc — APPROVED** [review]
LGTM

**Comment by t25kim** [comment]
> > > Description can be little more for any third person to understand like why we do the change and how. Understand we are fixing an issue #278 . Later date when we check the PR, better description would be good and we need not to go to issue also.
> > 
> > 
> > Please see [65a801d](https://github.com/lf-edge/edge-home-orchestration-go/commit/65a801da31888b0053500d0d591ac328f5759819). Seems it has an enough description in the commit message. Any issue from you?
> 
> Had checked the message. Why removal of PKG_LST can be little more explained is what I wanted to say. Was following : "We explain our solution and why we are doing what we are doing, as opposed to describing what we are doing."



> > > Why removal of PKG_LST can be little more explained is what I wanted to say.
> > 
> > 
> > @suresh-lc It is well explained with the linked issue #278. Plus there is a description why need this commit (reduce of LoC). In addition to that, I would like to recommend you to also provide your rectified recommendation if you truly want an improved revision from contributors, otherwise, the discussion will go to a lot of chats and overheads.
> 
> @MoonkiHong : thanks for your comments. Ya had mentioned that we are resolving the issue #278 . Since wanted to improve the contributions , had given the comment and not to just have chats, guess my intention was not rightly conveyed, sorry for that.

@suresh-lc Thank you for sharing your idea. 
I thought `PKG_LIST` is not necessary because developers can run TC without PKG_LIST and maintaining `PKG_LIST` needs many efforts without worth (`It only consumes LoC`).
If someone needs the code, I can leave the code as is.
Please tell us without hesitation if you think we need to maintain some code!

**Pull request merged**
