### PR TITLE
Add OpenSSF Scoring Card analysis to github->action workflow

### LINKED ISSUE #399: OpenSSF ScoreCard status of the Edge-Orchestration
[OpenSSF ScoreCard](https://github.com/ossf/scorecard) status of the Edge-Orchestration project
| SCORE_   | NAME               | REASON                                                                                    |
|----------|------------------------|---------------------------------------------------------------------------------------|
| 10 / 10 | Binary-Artifacts       | no binaries found in the repo                                                         |
| 0 / 10  | Branch-Protection      | branch protection not enabled on development/release branches                         |
| 10 / 10 | CI-Tests               | 30 out of 30 merged PRs checked by a CI test -- score normalized to 10                |
| 7 / 10  | CII-Best-Practices     | badge detected: silver                                                                |
| 10 / 10 | Code-Review            | GitHub code reviews                                                                   |
| 10 / 10 | Code-Review            | GitHub code reviews found for 30 commits out of the last 30 -- score normalized to 10 |
| 10 / 10 | Contributors           | 3 different companies found -- score normalized to 10                                 |
| 0 / 10  | Dependency-Update-Tool | no update tool detected                                                               |
| 0 / 10  | Fuzzing                | project is not fuzzed in OSS-Fuzz                                                     |
| 10 / 10 | Maintained             | 30 commit(s) found in the last  90 days -- score normalized to  10                    |
| ?       | Packaging              | no published package detected                                                         |
| 5 / 10  | Pinned-Dependencies    | unpinned dependencies detected -- score normalized to 5                               |
| 10 / 10 | SAST                   | SAST tool is run on all commits                                                       |
| 0 / 10  | Security-Policy        | security policy file not detected                                                     |
| 10 / 10 | Signed-Releases        | 5 out of 5 artifacts are signed -- score normalized to 10                             |
| 0 / 10  | Token-Permissions      | non read-only tokens detected  in GitHub workflows                                    |
| 10 / 10 | Vulnerabilities        | no vulnerabilities detected                                                           |

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

This is an attempt to integrate the [OpenSSF ScoreCards](https://github.com/ossf/scorecard) into our repository. If successful, we will see items that do not meet the requirements of the OpenSSF requiremets in the Security tab.
Workflow is set to run once a week. 

Fixes #399 

## Type of change

- [x] CI system update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
LGTM. Good to start with for the OpenSSF Scoring Card analysis for our project. Thank you.

**Comment by tdrozdovsky** [comment]
> LGTM. Good to start with for the OpenSSF Scoring Card analysis for our project. Thank you.

If you have the opportunity to merge this PR, so that we can see if there is a result for the weekend. Since I tried to use a temporary token for this operation (in order not to declare a personal token to the LF Edge admin command)

**Review by suresh-lc — APPROVED** [review]
+1, thanks for adding OpenSSF scoring card

**Review by t25kim — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
