### PR TITLE
Fixed a blocking by calling it in a go routine

### PR DESCRIPTION
**Pull request by ayush-kr**
Signed-off-by: ayush.kumar <ayush.kumar@samsung.com>
Co-authored-by: MoonkiHong <moonki1.hong@samsung.com>

# Description

Fixed a blocking call to edgex package by calling it in go routine. The startup.Bootstrap(...) call was blocking the control and the code below that was failing to execute.
This call is now made in go routine, so it won't block the execution and code flow will happen normally.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
```
$ ./build.sh mnedcserver
```

MNEDC related code was below the call to startup.Bootstrap(...), it was not getting executed, since the call was blocking.

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by suresh-lc — APPROVED** [review]
Making the go routine to avoid blocking call. LGTM.

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Comment by MoonkiHong** [comment]
@suresh-lc @ayush-kr I will resolve the merge conflict tomorrow morning.

**Review by MoonkiHong — CHANGES_REQUESTED** [review]
Will resolve the conflict.

**Comment by MoonkiHong** [comment]
@ayush-kr Please check out the current version with the merged PR #159 if this blocking issue is reproduced.

**Review by MoonkiHong — APPROVED** [review]
> @ayush-kr Please check out the current version with the merged PR #159 if this blocking issue is reproduced.

Conflict resolved with also applying #159. Verified.

**Pull request merged**
