### PR TITLE
TOML bug fix derived from version update

### LINKED ISSUE #528: Panic
After #521 PR merged, Edge Orchestration container running with DataStorage goes to panic.

### How to Reproduce
Run according to the [instruction](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/datastorage.md#4-how-to-run).

### LOG
```
NFO[2022-03-17T23:36:34Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-edd52da3-fcce-4180-aed4-6ff75e18384e
INFO[2022-03-17T23:36:34Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker)
INFO[2022-03-17T23:36:34Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([10.113.171.81]), RTT(0)
INFO[2022-03-17T23:36:34Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([DataStorage])
INFO[2022-03-17T23:36:34Z]discovery.go:578 func1
panic: interface conversion: interface {} is nil, not string

goroutine 68 [running]:
github.com/lf-edge/edge-home-orchestration-go/internal/controller/storagemgr/config.GetMetadataServerIP({0xcc14d4, 0x7})
        /home/t25kim/work/edge-home-orchestration-go/internal/controller/storagemgr/config/toml.go:189 +0xd6
github.com/lf-edge/edge-home-orchestration-go/internal/controller/storagemgr.checkMetadataStatus()
        /home/t25kim/work/edge-home-orchestration-go/internal/controller/storagemgr/storage.go:89 +0x29
github.com/lf-edge/edge-home-orchestration-go/internal/controller/storagemgr.(*StorageImpl).StartStorage(0xc000304480, {0xc00060c2e0, 0xcb8345})
        /home/t25kim/work/edge-home-orchestration-go/internal/controller/storagemgr/storage.go:123 +0x1c5
github.com/lf-edge/edge-home-orchestration-go/internal/controller/discoverymgr.deviceDetectionRoutine.func1()
        /home/t25kim/work/edge-home-orchestration-go/internal/controller/discoverymgr/discovery.go:595 +0x93a
created by github.com/lf-edge/edge-home-orchestration-go/internal/controller/discoverymgr.deviceDetectionRoutine
        /home/t25kim/work/edge-home-orchestration-go/internal/controller/discoverymgr/discovery.go:550 +0x25
```

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Fixes #528

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Run according to the [instruction](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/datastorage.md#4-how-to-run).

**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64
* Edge Orchestration Release: v1.1.9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tdrozdovsky — APPROVED** [review]
Great job! When I watched the changes, I forgot what needs to be changed in [accordance](https://github.com/pelletier/go-toml#usage-example). Thank you for correcting my mistake!

**Comment by t25kim** [comment]
> Great job! When I watched the changes, I forgot what needs to be changed in [accordance](https://github.com/pelletier/go-toml#usage-example). Thank you for correcting my mistake!

Thanks! I know this is not your mistake. I learned test code is important and will implement the test code to avoid similar problems.

**Review by MoonkiHong — COMMENTED** [review]
LGTM. :D

**Review by MoonkiHong — APPROVED** [review]

**Review by suresh-lc — APPROVED** [review]
+1

**Pull request merged**
