### PR TITLE
Add github.com/grandcat/zeroconf@v1.0.0 to third_party/zeroconf/

### PR DESCRIPTION
**Pull request by t25kim**
- apply a git patch (controller/discoverymgr/wrapper/zeroconfEdgeOrchestration.patch)

Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Import `zeroconf` open source project within `third_party` directory for ease of CI.

## Type of change

- [x] Code cleanup/refactoring
- [x] This change requires a documentation update 

# How Has This Been Tested?
$ ./build

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — COMMENTED** [review]
@t25kim Thank you for this wonderful job! I have a question (seems trivial at this moment though) in this PR.

- Does this PR have any new added/revised contribution on top of the existing 3rd party zeroconf source code? Or just employ the existing zeroconf codes into the given folder? [:>] Thank you in advance. 😄

**Comment by MoonkiHong** [comment]
Once this PR is reviewed and merged, then I will modify the regarding document in `README.md` to present the license matter about the zeroconf clearly (with a creation of GitHub issue for the regarding task).

**Comment by t25kim** [comment]
> @t25kim Thank you for this wonderful job! I have a question (seems trivial at this moment though) in this PR.
> 
> * Does this PR have any new added/revised contribution on top of the existing 3rd party zeroconf source code? Or just employ the existing zeroconf codes into the given folder? [:>] Thank you in advance. 😄

This PR has source code derived from the [patch set](https://github.com/lf-edge/edge-home-orchestration-go/blob/c02c1be96ecf39d9e14c713a4a211a606337c511/src/controller/discoverymgr/wrapper/zeroconfEdgeOrchestration.patch).
Thanks!

**Comment by MoonkiHong** [comment]
> > @t25kim Thank you for this wonderful job! I have a question (seems trivial at this moment though) in this PR.
> > 
> > * Does this PR have any new added/revised contribution on top of the existing 3rd party zeroconf source code? Or just employ the existing zeroconf codes into the given folder? [:>] Thank you in advance. 😄
> 
> This PR has source code derived from the [patch set](https://github.com/lf-edge/edge-home-orchestration-go/blob/c02c1be96ecf39d9e14c713a4a211a606337c511/src/controller/discoverymgr/wrapper/zeroconfEdgeOrchestration.patch).
> Thanks!

@t25kim Thank you for the kind clarification! 😄

**Review by MoonkiHong — APPROVED** [review]
LGTM. Really appreciate this wonderful PR. It is also clearly verified if there is any compliance/license issue if we embrace the 3rd party source codes into the external folder in our project. (No issue)

**Comment by tdrozdovsky** [comment]
@t25kim I appreciate your efforts to improve our project, but I would like to know what is the reason for adding 3rd party source code to our repository?

P.S. Perhaps this is due to the issue of your PR #249.
If yes, then I want to inform you that by slightly changing the code of your PR #249, I achieved a stable build (at least on my PC). Tomorrow I will contact you using a messenger or a message in a PR #249 and show my changes.
I hope we can fix the Native and Android Build together!

**Comment by t25kim** [comment]
> @t25kim I appreciate your efforts to improve our project, but I would like to know what is the reason for adding 3rd party source code to our repository?
> 
> P.S. Perhaps this is due to the issue of your PR #249.
> If yes, then I want to inform you that by slightly changing the code of your PR #249, I achieved a stable build (at least on my PC). Tomorrow I will contact you using a messenger or a message in a PR #249 and show my changes.
> **I hope we can fix the Native and Android Build together!**

Look forward to hearing your advice!

**Review by tdrozdovsky — APPROVED** [review]

**Pull request merged**
