### PR TITLE
Update testing guide

### LINKED ISSUE #350: Testing Guide Update
[Testing Policy](https://github.com/lf-edge/edge-home-orchestration-go/blob/6bc65c06d21b1c46f64818521f5ab3a22adab9a2/docs/testing_policy.md) should have how to install coverage tool (gocov and gocov-html).

**Error Log when coverage tools are not installed.**
```
t25kim@t25kim:~/work/edge-home-orchestration-go$ make test
.
.
--------------------------------------
  build test for internal/...
--------------------------------------
make test-go TEST_PKG_DIRS="internal/..."
make[1]: Entering directory '/home/t25kim/work/edge-home-orchestration-go'
gocov test -v ./internal/... > coverage.out
/bin/sh: 1: gocov: not found
```
```
t25kim@t25kim:~/work/edge-home-orchestration-go$ go get github.com/axw/gocov/gocov
go get: added github.com/axw/gocov v1.0.0
t25kim@t25kim:~/work/edge-home-orchestration-go$ make test
.
.
github.com/lf-edge/edge-home-orchestration-go/internal/restinterface/tls/tls.go  SetHandler                              0.00% (0/1)
github.com/lf-edge/edge-home-orchestration-go/internal/restinterface/tls         -------------------------------------   94.44% (17/18)

Total Coverage: 73.75% (3071/4164)
gocov-html coverage.out > coverage.html
/bin/sh: 1: gocov-html: not found
```

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Adds instructions on how to install the `gocov` package and `staticckeck` tool for testing the project. 
Fixes #350

## Type of change

- [ ] Documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — COMMENTED** [review]
Thanks for quick contribution.
We also need an installation guide for `gocov-html`.

**Comment by tdrozdovsky** [comment]
> 
> 
> Thanks for quick contribution.
> We also need an installation guide for `gocov-html`.

Thank you! Done!

**Review by t25kim — APPROVED** [review]
LGTM Thanks!

**Review by MoonkiHong — APPROVED** [review]
+1

**Pull request merged**
