### PR TITLE
Migrate to Go Modules and update docker engine to v19.03.14

### LINKED ISSUE #206: [Build System] Applying Go Modules instead of relying on Glide
**Is your feature request related to a problem? Please describe.**
The current edge-home-orchestration-go project is built from employing `glide`. Consequently, it is really challenging for us to employ those existing available open source projects based on the Go Modules build system. One good example is that we cannot apply the latest version of Docker Engine and the recent EdgeX features, which all are based on Go Modules. In addition to make this situation much worse, the 3rd party developers might encounter a huge difficulty in building their own applications powered by edge-home-orchestration-go, because most of them are using Go Modules instead of Glide. Especially, if there is a developer to use some subset of edge-home-orchestration-go, he/she should fully describe the regarding GitHub url about those subset packages into their `import` like `github.com/lf-edge/edge-home-orchestration-go/src/common/logmgr` instead of `common/logmgr`.

**Describe the solution you'd like**
Applying the new build system based on Go Modules and deprecating the Glide based build system.

- https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md
- https://github.com/golang/go/wiki/Modules

**Suggestion: LET US discuss this issue in the upcoming TSC online meeting in January 2021!!!**

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25kim@samsung.com>

# Description
This PR is to support [go modules](https://github.com/golang/go/wiki/Modules).
Updating Docker pkgs to v19 since some pkgs conflicts with the docker v17.

Fixes #206 #207 

## Type of change

- [x] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update

# How Has This Been Tested?
This PR has only been tested in terms of container without security.
./build.sh

**Test Configuration**:
* Firmware version: Ubuntu 18.04, RPi2
* Toolchain: (e.g., Docker and Go 15) 
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MoonkiHong** [comment]
@tdrozdovsky Since this PR has been tested without security, I would like to recommend you to complete the test with security flag in building and let us know its result. Thank you in advance.

**Review by MoonkiHong — COMMENTED** [review]
Overall it seems good to me to go. Once @tdrozdovsky shares his evaluation with the `secure` build option including this PR. we can merge it in a timely manner.

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Review by tdrozdovsky — APPROVED** [review]
LGTM
I checked this PR on Ubuntu 16.04 and 18.04 in `normal` and `secure` mode: It works great!
The first step has been successfully completed! Thank you @t25kim for your important contribution to our project.

**Pull request merged**
