### PR TITLE
[DO NOT MERGE] Basic Template generated by Angular for WebUI

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Related #425 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
### Angular CLI
1. Setup [Angular dev environment](https://angular.io/guide/setup-local)
2. Go to `web` folder and install node modules with command "npm install"
3. Run node server and access the web page like `http://localhost:4200/`

### Edge Orchestration Container
1. Run `Edge Orchestration` with `WEBUI` environment variable like below.
```
docker run -it -d --privileged --network="host" --name edge-orchestration -e WEBUI=true -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro lfedge/edge-home-orchestration-go:latest
```
2. Access the web page like `http://localhost:49153`

**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64
* Edge Orchestration Release: v1.1.4

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
+1

**Review by MoonkiHong — APPROVED** [review]
LGTM. 😁

**Review by tdrozdovsky — APPROVED** [review]
I have little experience in developing web pages, and I hope you understand the complexity of generating a page with using Angular (the problem of matching component versions)

**Comment by t25kim** [comment]
> I have little experience in developing web pages, and I hope you understand the complexity of generating a page with using Angular (the problem of matching component versions)

Thanks for your kind comment. It really helps me since I'm new to Angular. I chose Angular for two reasons. 
I referred to the [edgex-ui-go](https://github.com/edgexfoundry/edgex-ui-go) of edgexfoundry. Also I've monitored SOSHUB FE code, and believe Ukraine folks can help us if we got stuck.😁

**Comment by t25kim** [comment]
We will take `React` instead of Angular.

**Pull request closed without merging**
