### PR TITLE
[Refactoring] Add a variable storing cipher algorithm for ease of use

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

There are many function calls to set cipher algorithm in orchestrationInit().
Once it is set, the same algorithm will be used continuously to improve convenience and consistency.

Related #275 

## Type of change

- [x] Code cleanup/refactoring

# How Has This Been Tested?
Offload a hello-world container to other edge-orchestrator

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
@tdrozdovsky Could you please verify this PR in terms of `secure` mode?

**Comment by tdrozdovsky** [comment]
Looks good, but you need to do the same in the `cmd/edge-orchestration/javaapi/javaapi.go` and `cmd/edge-orchestration/capi/main.go` files

**Comment by MoonkiHong** [comment]
> Looks good, but you need to do the same in the `cmd/edge-orchestration/javaapi/javaapi.go` and `cmd/edge-orchestration/capi/main.go` files

Before going into the additional suggestion, let us estimate if the feature support for native and Android is ready for us. The reason is - still we need more careful investigation of the use case and usability in terms of native and Android. So before that preparation, my suggestion is to separate the approach for covering any feature supports for native and Android from our current version (a.k.a. container). What do you think?

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Review by MoonkiHong — APPROVED** [review]
+1

**Pull request merged**
