### PR TITLE
[DataStorage] Add SetYaml function for DataStorage configuration

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

This PR is intended to create DataStorage's configuration file, such as [datastorage-device.yaml](https://github.com/lf-edge/edge-home-orchestration-go/blob/79a18bcc14220e3c47a3d47c19a968ca7e0417cf/configs/datastorage/datastorage-device.yaml) dynamically.

Related #302

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Run TC and compare the result to the [configs/datastorage/datastorage-device.yaml](https://github.com/lf-edge/edge-home-orchestration-go/blob/79a18bcc14220e3c47a3d47c19a968ca7e0417cf/configs/datastorage/datastorage-device.yaml) file.
$ go test -v ./internal/controller/storagemgr/config/

## RESULT
```
INFO[2021-06-08T19:30:24+09:00]yaml_test.go:112 TestYaml 
name: datastorage
manufacturer: Home Edge
model: Home Edge
labels:
- rest
- json
- numeric
- float
- int
description: REST Device
deviceResources:
- name: json
  description: json
  properties:
    value: {type: String, readWrite: RW, mediaType: application/json}
    units: {type: String, readWrite: R}
- name: int
  properties:
    value: {type: Int64, readWrite: RW, mediaType: text/plain}
    units: {type: String, readWrite: R}
- name: float
  description: float
  properties:
    value: {type: Float64, readWrite: RW, mediaType: text/plain}
    units: {type: String, readWrite: R}
- name: jpeg
  description: jpeg
  properties:
    value: {type: Binary, readWrite: RW, mediaType: image/jpeg}
    units: {type: String, readWrite: R}
- name: png
  description: png
  properties:
    value: {type: Binary, readWrite: RW, mediaType: image/png}
    units: {type: String, readWrite: R}
- name: string
  description: string
  properties:
    value: {type: String, readWrite: RW, mediaType: text/plain}
    units: {type: String, readWrite: R}
```

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
LGTM. Thank you for your contribution! 😄

**Review by suresh-lc — APPROVED** [review]
Thanks for the contribution

**Comment by MoonkiHong** [comment]
@tdrozdovsky PTAL. ^^

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Pull request merged**
