### PR TITLE
Update version (v1.1.3)

### PR DESCRIPTION
**Pull request by MoonkiHong**
Signed-off-by: MoonkiHong <moonki1.hong@samsung.com>

Update list
- Add initial prototype of Web UI (PR#434)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tdrozdovsky** [comment]
I'm a little confused. What is the reason for increasing the patch number every week? According to the [Semantic Versioning Specification](https://semver.org/), point 6: _"Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior."_. 
We haven't fixed any bugs this week.  **Or is there a requirement that we make a patch every week?**

**Comment by tdrozdovsky** [comment]
If need to release a new version, then, given the changes (Add initial prototype of Web UI (PR#434) is new feature), it is more correct to release version 1.2.0

**Comment by MoonkiHong** [comment]
> I'm a little confused. What is the reason for increasing the patch number every week? According to the [Semantic Versioning Specification](https://semver.org/), point 6: _"Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior."_. We haven't fixed any bugs this week. **Or is there a requirement that we make a patch every week?**

It is not a requirement, but **it is to officialize our progress in a weekly manner.**

**Comment by MoonkiHong** [comment]
> If need to release a new version, then, given the changes (Add initial prototype of Web UI (PR#434) is new feature), it is more correct to release version 1.2.0

Make sense.

**Comment by tdrozdovsky** [comment]
I am currently working on fixing the CWE-117. You can give me 3 hours (I'll try to finish.  but it is not 100%), and then we can correctly release 1.1.3

**Comment by MoonkiHong** [comment]
> I am currently working on fixing the CWE-117. You can give me 3 hours (I'll try to finish. but it is not 100%), and then we can correctly release 1.1.3

Make sense. Then I will close this PR without merge and wait for yours. We can release the tag of 1.1.3 early next week. 😁

**Comment by tdrozdovsky** [comment]
@MoonkiHong I already know how to fix it, but it takes more time to fix them (56)

**Pull request closed without merging**
