### PR TITLE
[ScoringManager] Change the score API from GET to POST

### PR DESCRIPTION
**Pull request by nitu-s-gupta**
Signed-off-by: Nitu Gupta <nitu.gupta@samsung.com>

# Description

API to get score required a request body with id of the device. But GET request body adds no meaning and the ID of the devices has to be passed in encrypted form for secure mode. So the API is changed method from GET to POST

API is
http://{IP of the device which will calculate score}:56002/scoringmgr/score

Fixes #610 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. Start the Edge Orchestration and run the following curl command to execute the hello-world coontainer. This API will internally calculate the score and display on the terminal
Example
```
curl -X POST "127.0.0.1:56001/api/v1/orchestration/services" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: $EDGE_ORCHESTRATION_TOKEN" -d "{ \"ServiceName\": \"hello-world\", \"ServiceInfo\": [{ \"ExecutionType\": \"container\", \"ExecCmd\": [ \"docker\", \"run\", \"-v\", \"/var/run:/var/run:rw\", \"hello-world@sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752\"]}]}"
```
Response Generated is 
```
{"Message":"ERROR_NONE","RemoteTargetInfo":{"ExecutionType":"container","Target":"192.168.1.108"},"ServiceName":"hello-world"}
```
2. The logs generated for Edge-Orchestration is 
```
INFO[2022-08-25T06:28:19Z]externalhandler.go:123 APIV1RequestServicePost [RestExternalInterface] APIV1RequestServicePost 
INFO[2022-08-25T06:28:19Z]externalhandler.go:187 APIV1RequestServicePost [RestExternalInterface] port: 59332          
INFO[2022-08-25T06:28:19Z]externalhandler.go:192 APIV1RequestServicePost [RestExternalInterface] requester: curl      
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:153 RequestService [RequestService] hello-world: [{container [docker run -v /var/run:/var/run:rw hello-world@sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752] map[]}] 
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:183 RequestService [RequestService] getCandidate                
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:185 RequestService [0] ID       : edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:186 RequestService [0] ExecType : container                     
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:187 RequestService [0] Endpoint : [192.168.1.108]               
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:188 RequestService                                              
INFO[2022-08-25T06:28:19Z]restclient.go:128 DoScoreRemoteDevice [restclient] DoScoreRemoteDevice : endpoint[192.168.1.108] 
INFO[2022-08-25T06:28:19Z]internalhandler.go:250 APIV1ScoringmgrScoreLibnamePost [RestInternalInterface] APIV1ScoringmgrScoreLibnamePost 
INFO[2022-08-25T06:28:19Z]route.go:132 func1 From [192.168.1.108:52548] POST /api/v1/scoringmgr/score APIV1ScoringmgrScoreLibnamePost 546.237µs 
INFO[2022-08-25T06:28:19Z]restclient.go:153 DoScoreRemoteDevice [restclient] respMsg From [192.168.1.108] : map[ScoreValue:10.002320359566955] 
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:367 func3 [orchestrationapi] deviceScore               
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:368 func3 candidate ID       : edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:369 func3 candidate ExecType : container               
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:370 func3 candidate Endpoint : 192.168.1.108           
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:371 func3 candidate score    : 10.002320359566955      
INFO[2022-08-25T06:28:19Z]orchestrationapi.go:273 RequestService [orchestrationapi]  [{edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 192.168.1.108 10.002320359566955 map[] container}] 
INFO[2022-08-25T06:28:19Z]route.go:132 func1 From [127.0.0.1:59332] POST /api/v1/orchestration/services APIV1RequestServicePost 64.3596ms 
INFO[2022-08-25T06:28:19Z]containerexecutor.go:71 Execute [containerexecutor] hello-world docker run -v /var/run:/var/run:rw -e REQUEST=192.168.1.108 hello-world@sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752 
INFO[2022-08-25T06:28:19Z]containerexecutor.go:72 Execute [containerexecutor] parameter length : 7     
{"status":"Pulling from library/hello-world","id":"docker.io/library/hello-world@sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752"}
{"status":"Digest: sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752"}
{"status":"Status: Image is up to date for hello-world@sha256:fc6a51919cfeb2e6763f62b6d9e8815acbf7cd2e476ea353743570610737b752"}
INFO[2022-08-25T06:28:23Z]containerexecutor.go:92 Execute [containerexecutor] create container : 76908c62ff 
2022-08-25T06:28:24.446297368Z 
2022-08-25T06:28:24.446397835Z Hello from Docker!
2022-08-25T06:28:24.446424951Z This message shows that your installation appears to be working correctly.
2022-08-25T06:28:24.446446793Z 
2022-08-25T06:28:24.446466092Z To generate this message, Docker took the following steps:
2022-08-25T06:28:24.446485874Z  1. The Docker client contacted the Docker daemon.
2022-08-25T06:28:24.446505724Z  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
2022-08-25T06:28:24.446526431Z     (amd64)
2022-08-25T06:28:24.446545426Z  3. The Docker daemon created a new container from that image which runs the
2022-08-25T06:28:24.446565317Z     executable that produces the output you are currently reading.
2022-08-25T06:28:24.446585026Z  4. The Docker daemon streamed that output to the Docker client, which sent it
2022-08-25T06:28:24.446605098Z     to your terminal.
2022-08-25T06:28:24.446624185Z 
2022-08-25T06:28:24.446643065Z To try something more ambitious, you can run an Ubuntu container with:
2022-08-25T06:28:24.446662787Z  $ docker run -it ubuntu bash
2022-08-25T06:28:24.446682589Z 
2022-08-25T06:28:24.446701493Z Share images, automate workflows, and more with a free Docker ID:
2022-08-25T06:28:24.446721065Z  https://hub.docker.com/
2022-08-25T06:28:24.446740065Z 
2022-08-25T06:28:24.446759416Z For more examples and ideas, visit:
2022-08-25T06:28:24.446779138Z  https://docs.docker.com/get-started/
2022-08-25T06:28:24.446798260Z 
INFO[2022-08-25T06:28:26Z]containerexecutor.go:118 Execute [containerexecutor] container execution status : 0 
INFO[2022-08-25T06:28:26Z]orchestrationapi.go:475 listenNotify [orchestrationapi] service status changed [appNames:hello-world][status:Finished] 
INFO[2022-08-25T06:28:44Z]discovery.go:860 activeDiscovery [discoverymgr] activeDiscovery!!!            
INFO[2022-08-25T06:28:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:28:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:28:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:28:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:28:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:28:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:28:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:28:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:28:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:28:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:29:44Z]discovery.go:860 activeDiscovery [discoverymgr] activeDiscovery!!!            
INFO[2022-08-25T06:29:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:29:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:29:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:29:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:29:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:29:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:29:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:29:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:29:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:29:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:30:44Z]discovery.go:860 activeDiscovery [discoverymgr] activeDiscovery!!!            
INFO[2022-08-25T06:30:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:30:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:30:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:30:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:30:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:30:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:30:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:30:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:30:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
INFO[2022-08-25T06:30:44Z]discovery.go:578 func1                                              
INFO[2022-08-25T06:31:44Z]discovery.go:860 activeDiscovery [discoverymgr] activeDiscovery!!!            
INFO[2022-08-25T06:31:44Z]discovery.go:574 func1 [deviceDetectionRoutine] edge-orchestration-314b6cd6-a8af-46ea-a3a8-452495c8b02e 
INFO[2022-08-25T06:31:44Z]discovery.go:575 func1 [deviceDetectionRoutine] confInfo    : ExecType(container), Platform(docker) 
INFO[2022-08-25T06:31:44Z]discovery.go:576 func1 [deviceDetectionRoutine] netInfo     : IPv4([192.168.1.108]), RTT(0) 
INFO[2022-08-25T06:31:44Z]discovery.go:577 func1 [deviceDetectionRoutine] serviceInfo : Services([AISER DataStorage TEST]) 
````
**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64 (e.g., x86, x86-64, arm, arm64)
* Toolchain: Docker v20.10 & Go v1.16
* Edge Orchestration Release: v1.1.1

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM!

**Review by suresh-lc — APPROVED** [review]
LGTM, Thanks for the kind analysis and making the suggestion

**Review by MoonkiHong — APPROVED** [review]
It looks good to me. 😄

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Pull request merged**
