### PR TITLE
[DataStorage] Moving the device SDK to third party folder (Issue #386)

### PR DESCRIPTION
**Pull request by rb29**
Signed-off-by: rb29 <raina.rb29@gmail.com>

# Description

Edge Orchestration uses edgexfoundry/device-sdk-go from github.com/hahattan/device-sdk-go v1.4.1, not the official repository, So the repository is moved to third party folder

Fixes # (#386)

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. The folder is moved to the third party folder
2. The code is build and edge-orchestration is run
3. The device gets added successfully
4. All the APIs were tested and they ran successfully

**Test Configuration**:
* OS type & version: (Ubuntu 20.04)
* Hardware: ( x86-64)
* Edge Orchestration Release: (1.0.0)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
Thank you for your contribution. Related to #386, we need this one and verified from the GH actions that there is no issue. +1

**Review by t25kim — APPROVED** [review]
LGTM. Thanks for the help!

**Review by suresh-lc — APPROVED** [review]
LGTM.

**Comment by t25kim** [comment]
Instead of copying the code, we use official edgexfoundry/device-sdk-go v1.4.0 and fix the [bug](https://github.com/lf-edge/edge-home-orchestration-go/issues/231).

**Pull request closed without merging**
