### PR TITLE
Fix securemgr lint warnings

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Fix warnings found by linter in the security manager.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code cleanup/refactoring

# How Has This Been Tested?
See result of Test Suite

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tdrozdovsky** [comment]
And here is the first experience with SonarCloud: a commit changes some constants and, as a result, the lines are similar. I think this remark from Sonar can be ignored! 
And also lint and vet work automatically on my fork, which helped to immediately detect the error!

Testing our code is now much easier.

**I'm proud that we did this job!**

**Comment by t25kim** [comment]
> 
> 
> And here is the first experience with SonarCloud: a commit changes some constants and, as a result, the lines are similar. I think this remark from Sonar (3.1% Duplication) can be ignored!
> And also lint and vet work automatically on my fork, which helped to immediately detect the error!
> 
> Testing our code is now much easier.
> 
> **I'm proud that we did this job!**

Thank you very much for your great contribution! It was impossible without you.  

You mentioned `remark from Sonar can be ignored` but I think we should get it more seriously since many PRs to come will be marked as `failures` by SonarCloud Analysis. 
If we want to ignore the SonarCloud results, we need to make the SonarCloud Analysis results `successful` regardless of the value of `Duplicated Lines`.

**Comment by MoonkiHong** [comment]
> And here is the first experience with SonarCloud: a commit changes some constants and, as a result, the lines are similar. I think this remark from Sonar (3.1% Duplication) can be ignored!
> And also lint and vet work automatically on my fork, which helped to immediately detect the error!
> 
> Testing our code is now much easier.
> 
> **I'm proud that we did this job!**

@tdrozdovsky It seems okay just focusing on the diff. from this PR in terms of code duplication, but let us be more careful to take the analysis result from SonarCloud. It anyways estimates some code duplication for several source codes in our project, and we at least take a look at it. What do you think?

**Review by t25kim — APPROVED** [review]
LGTM. Thanks!

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
