### PR TITLE
Fix CWE-117

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Fix [CWE-117](https://cwe.mitre.org/data/definitions/117.html). I would like to note that the task is more difficult than it seems at first glance. The reason is that the LGTM(CodeQL) does not have the correct template for solving this problem. It can be argued that the vulnerability has been fixed, but the LGTM cannot detect this fix. Hence each line is marked as excluded. I have not excluded this type of error for the entire project, since the vulnerability is serious. And we will have to fix it every time it appears. Sometimes the lines of code became out very long, I didn't want to do that, but I had to.
I hope this is a temporary solution, and a nicer solution will be found. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Below is just an example and you can delete it when you contribute.

**Test Configuration**:
* OS type & version: Ubuntu 18.04
* Hardware: x86-64
* Toolchain: Docker v20.04 and Go v1.16
* Edge Orchestration Release: v1.1.2

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
LGTM. Thank you for your diligent effort to resolve the CWE-117 in time.

**Comment by tdrozdovsky** [comment]
After applying PR and updating the LGTM system, I will mark it in the CodeQL as "false positive"

**Comment by MoonkiHong** [comment]
> After applying PR and updating the LGTM system, I will mark it in the CodeQL as "false positive"

Copy that. 😁

**Review by t25kim — APPROVED** [review]
LGTM

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
