### PR TITLE
[Logmgr] Apply logmgr to most of source code

### PR DESCRIPTION
**Pull request by t25kim**
# Description

This PR replaces package log with logmgr for logging.
Related #182

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
See container's log.
```
docker logs -f edge-orchestration
```

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
This is great!!! Thank you @t25kim for your passionate and prompt contributions. LGTM!!!

**Review by MoonkiHong — APPROVED** [review]
LGTM. Another removal of `logrus`.

**Review by tdrozdovsky — APPROVED** [review]
Great first step!

**Review by suresh-lc — APPROVED** [review]
Good job in moving towards the open source way

**Pull request merged**
