### PR TITLE
Remove Ubuntu-16.04 as a target platform for build and test due to th…

### LINKED ISSUE #289: [SUSPENDED] Ubuntu Version
[Standard support for Ubuntu 16.04 LTS](https://wiki.ubuntu.com/Releases) ends in April 2021.
I'd like to
 1. exclude Ubuntu 16.04 from the [Build](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/.github/workflows/build.yml) and [Test Suite](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/.github/workflows/test-suite.yml) workflows.
 2. change the Ubuntu version of the [Dockerfile](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/Dockerfile) from 16.04 to 20.04.

### PR DESCRIPTION
**Pull request by tdrozdovsky**
…e end of the support of this OS

Signed-off-by: Taras Drozdovskyi <t.drozdovsky@gmail.com>

# Description

Remove Ubuntu-16.04 as a target platform for build and test due to the end of the support of this OS 

Fixes #289 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Successful ending of all github->Actions

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM. Thanks!

**Review by suresh-lc — APPROVED** [review]
LGTM.

**Review by MoonkiHong — APPROVED** [review]
LGTM. Thanks!

**Comment by MoonkiHong** [comment]
There is the upcoming patch that need to be integrated with this PR. Until that proposal, this PR will be suspended. (Just FYI)

**Comment by tdrozdovsky** [comment]
@MoonkiHong  In connection with the end of the official support of the Ubuntu 16.04 in the near future `The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead.`
I propose to apply this PR

**Review by t25kim — APPROVED** [review]
LGTM

**Pull request merged**
