### PR TITLE
Increase test coverage of securemgr

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Fixes some inaccuracies and increases test coverage of securemgr components

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
```
$ ./build.sh test authenticator
$ ./build.sh test authorizer
$ ./build.sh test verifier
```

**Test Configuration**:
* Firmware version: (OS type and version, e.g., Ubuntu 16.04, etc.)
* Hardware: x86-64
* Toolchain: Docker and Go recommended versions
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM! 

### TC logs
./build.sh test authenticator (35.71% → 41.07%)
[Current Result]
```
coverage: 35.7% of statements
ok      controller/securemgr/authenticator      0.002s  coverage: 35.7% of statements
gocov report coverage.out

controller/securemgr/authenticator/authenticator.go      randString      100.00% (4/4)
controller/securemgr/authenticator/authenticator.go      init            100.00% (1/1)
controller/securemgr/authenticator/authenticator.go      Init            68.18% (15/22)
controller/securemgr/authenticator/authenticator.go      @106:26         0.00% (0/18)
controller/securemgr/authenticator/authenticator.go      @127:58         0.00% (0/10)
controller/securemgr/authenticator/authenticator.go      @104:27         0.00% (0/1)
controller/securemgr/authenticator                       ----------      35.71% (20/56)

Total Coverage: 35.71% (20/56)
```
[PR Result]
```
coverage: 41.1% of statements
ok      controller/securemgr/authenticator      0.002s  coverage: 41.1% of statements
gocov report coverage.out

controller/securemgr/authenticator/authenticator.go      randString      100.00% (4/4)
controller/securemgr/authenticator/authenticator.go      init            100.00% (1/1)
controller/securemgr/authenticator/authenticator.go      Init            81.82% (18/22)
controller/securemgr/authenticator/authenticator.go      @106:26         0.00% (0/18)
controller/securemgr/authenticator/authenticator.go      @127:58         0.00% (0/10)
controller/securemgr/authenticator/authenticator.go      @104:27         0.00% (0/1)
controller/securemgr/authenticator                       ----------      41.07% (23/56)

Total Coverage: 41.07% (23/56)
```
./build.sh test authorizer (84.62% → 92.31%)
[Current Result] 
```
coverage: 84.6% of statements
ok      controller/securemgr/authorizer 0.003s  coverage: 84.6% of statements
gocov report coverage.out

controller/securemgr/authorizer/authorizer.go    Users.findByName        100.00% (4/4)
controller/securemgr/authorizer/authorizer.go    init                    100.00% (1/1)
controller/securemgr/authorizer/authorizer.go    Authorizer              86.67% (13/15)
controller/securemgr/authorizer/authorizer.go    Init                    78.95% (15/19)
controller/securemgr/authorizer                  ----------------        84.62% (33/39)

Total Coverage: 84.62% (33/39)
```
[PR Result]
```
coverage: 92.3% of statements
ok      controller/securemgr/authorizer 0.002s  coverage: 92.3% of statements
gocov report coverage.out

controller/securemgr/authorizer/authorizer.go    Users.findByName        100.00% (4/4)
controller/securemgr/authorizer/authorizer.go    init                    100.00% (1/1)
controller/securemgr/authorizer/authorizer.go    Init                    94.74% (18/19)
controller/securemgr/authorizer/authorizer.go    Authorizer              86.67% (13/15)
controller/securemgr/authorizer                  ----------------        92.31% (36/39)

Total Coverage: 92.31% (36/39)
```
./build.sh test verifier (92.79% → 93.69%)
[Current Result]
```
coverage: 92.8% of statements
ok      controller/securemgr/verifier   0.006s  coverage: 92.8% of statements
gocov report coverage.out

controller/securemgr/verifier/verifier.go        VerifierImpl.ContainerIsInWhiteList     100.00% (10/10)
controller/securemgr/verifier/verifier.go        initContainerWhiteList                  100.00% (10/10)
controller/securemgr/verifier/verifier.go        delAllHashFromContainerWhiteList        100.00% (7/7)
controller/securemgr/verifier/verifier.go        getIndexHashInContainerName             100.00% (5/5)
controller/securemgr/verifier/verifier.go        containerHashIsInWhiteList              100.00% (4/4)
controller/securemgr/verifier/verifier.go        printAllHashFromContainerWhiteList      100.00% (4/4)
controller/securemgr/verifier/verifier.go        GetInstance                             100.00% (1/1)
controller/securemgr/verifier/verifier.go        init                                    100.00% (1/1)
controller/securemgr/verifier/verifier.go        addHashToContainerWhiteList             91.67% (22/24)
controller/securemgr/verifier/verifier.go        delHashFromContainerWhiteList           90.48% (19/21)
controller/securemgr/verifier/verifier.go        Init                                    85.71% (6/7)
controller/securemgr/verifier/verifier.go        VerifierImpl.RequestVerifierConf        82.35% (14/17)
controller/securemgr/verifier                    -----------------------------------     92.79% (103/111)

Total Coverage: 92.79% (103/111)
```
[PR Result]
```
coverage: 93.7% of statements
ok      controller/securemgr/verifier   0.006s  coverage: 93.7% of statements
gocov report coverage.out

controller/securemgr/verifier/verifier.go        VerifierImpl.ContainerIsInWhiteList     100.00% (10/10)
controller/securemgr/verifier/verifier.go        initContainerWhiteList                  100.00% (10/10)
controller/securemgr/verifier/verifier.go        delAllHashFromContainerWhiteList        100.00% (7/7)
controller/securemgr/verifier/verifier.go        Init                                    100.00% (7/7)
controller/securemgr/verifier/verifier.go        getIndexHashInContainerName             100.00% (5/5)
controller/securemgr/verifier/verifier.go        containerHashIsInWhiteList              100.00% (4/4)
controller/securemgr/verifier/verifier.go        printAllHashFromContainerWhiteList      100.00% (4/4)
controller/securemgr/verifier/verifier.go        GetInstance                             100.00% (1/1)
controller/securemgr/verifier/verifier.go        init                                    100.00% (1/1)
controller/securemgr/verifier/verifier.go        addHashToContainerWhiteList             91.67% (22/24)
controller/securemgr/verifier/verifier.go        delHashFromContainerWhiteList           90.48% (19/21)
controller/securemgr/verifier/verifier.go        VerifierImpl.RequestVerifierConf        82.35% (14/17)
controller/securemgr/verifier                    -----------------------------------     93.69% (104/111)

Total Coverage: 93.69% (104/111)
```

**Comment by MoonkiHong** [comment]
@tdrozdovsky Thank you for your great proposal to improve the test coverage of the core security function of our community!
@t25kim Thank you for your passionate contribution to validate the suggested PR in a timely manner!!!

**Review by MoonkiHong — APPROVED** [review]
LGTM!

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
