### PR TITLE
[Workflow] CodeQL Analysis to detect security issues

### LINKED ISSUE #190: Code Scanning with CodeQL through github Actions
How about adding [CodeQL Analysis](https://github.com/lf-edge/edge-home-orchestration-go/security/code-scanning) to detect security issues with respect to source code?

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Add a CodeQL Analysis workflow to detect security issues with respect to source code
Fixes #190 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Open PR and see Actions workflows

**Result**
image

**Test Configuration**:
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
Integrating security validation through CodeQL Analysis (GitHub Action). LGTM.

@tdrozdovsky [This](https://github.com/lf-edge/edge-home-orchestration-go/pull/191/checks?check_run_id=1483287752) seems okay to me at this moment, but please let us know your opinion from the security perspective.

**Comment by MoonkiHong** [comment]
@suresh-lc @tdrozdovsky PTAL...

**Comment by tdrozdovsky** [comment]
@MoonkiHong @t25kim Sorry for the delay, but I really haven't fully understood the proposal yet.
perhaps we will duplicate the search for vulnerabilities because:
_CodeQL is the product that powers LGTM's community-driven security analysis. LGTM's analysis relies on queries written using CodeQL to check your code for security vulnerabilities, bugs, and errors. You can customize your LGTM analysis by writing custom queries that are specific to your project._

@t25kim Please share your thoughts, maybe I'm wrong. Overall, I like your proposal.

**Comment by MoonkiHong** [comment]
> @MoonkiHong @t25kim Sorry for the delay, but I really haven't fully understood the proposal yet.
> perhaps we will duplicate the search for vulnerabilities because:
> _CodeQL is the product that powers LGTM's community-driven security analysis. LGTM's analysis relies on queries written using CodeQL to check your code for security vulnerabilities, bugs, and errors. You can customize your LGTM analysis by writing custom queries that are specific to your project._
> 
> @t25kim Please share your thoughts, maybe I'm wrong. Overall, I like your proposal.

@tdrozdovsky This proposal also suggests to integrate its automated analysis per every PR, which is not yet facilitated from our community. ^^

**Comment by tdrozdovsky** [comment]
> 
> 
> > @MoonkiHong @t25kim Sorry for the delay, but I really haven't fully understood the proposal yet.
> > perhaps we will duplicate the search for vulnerabilities because:
> > _CodeQL is the product that powers LGTM's community-driven security analysis. LGTM's analysis relies on queries written using CodeQL to check your code for security vulnerabilities, bugs, and errors. You can customize your LGTM analysis by writing custom queries that are specific to your project._
> > @t25kim Please share your thoughts, maybe I'm wrong. Overall, I like your proposal.
> 
> @tdrozdovsky This proposal also suggests to integrate its automated analysis (any additional security vulnerability issues) per every PR before merged, which is not yet facilitated from our community. ^^

Yes, this is exactly what I like compared to LGTM when we see vulnerabilities after.

**Review by tdrozdovsky — APPROVED** [review]

**Comment by t25kim** [comment]
@MoonkiHong, @tdrozdovsky Thanks for the reivews!

> perhaps we will duplicate the search for vulnerabilities because:

I think so. The advantage is that it checks security issues of each PR through code scanning automatically before merged. so I opened the [issue](#190) to see community feedback if it is necessary or not.
How about merging this PR and seeing if it's useful?

**Comment by tdrozdovsky** [comment]
@t25kim @MoonkiHong This is a great idea, and as I wrote earlier, I really like it. In any case, I think it is necessary to try.
Let's try)))

**Pull request merged**
