### PR TITLE
Update the installation procedure of testing packages

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

Background:
When installing `gocov` and `gocov-html` packages with the `edge-home-orchestration-go ` folder, a description is added to the `go.mod` file. (go.mod is a tracked by the GitHub) The `go mod tidy` command makes check and optimize dependencies and since the packages are not included in the source code will be excluded from `go.mod`file. Therefore, `go.mod` file will always be marked as modified.

Update the installation procedure of `gocov` and `gocov-html`
 
## Type of change

- [x] Code cleanup/refactoring

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — COMMENTED** [review]
How about adding the `go.mod` file to the .gitignore instead of recommendations?

**Comment by tdrozdovsky** [comment]
If we exclude `go.mod` file from tracking, then after cloning, the repository will not have it. And we get a mistake like this:
`go: go.mod file not found in current directory or any parent directory; see 'go help modules'`

Or do you have other thoughts regarding this?

**Comment by t25kim** [comment]
> 
> 
> If we exclude `go.mod` file from tracking, then after cloning, the repository will not have it. And we get a mistake like this:
> `go: go.mod file not found in current directory or any parent directory; see 'go help modules'`
> 
> Or do you have other thoughts regarding this?

I was mistaken. I think your suggestion is the best at the moment.

**Review by t25kim — APPROVED** [review]
LGTM. Thanks!

**Review by MoonkiHong — APPROVED** [review]
+1

**Pull request merged**
