### PR TITLE
Fix all gofmt warnings

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

To get a [Go Report Card A+](https://goreportcard.com/report/github.com/lf-edge/edge-home-orchestration-go), it is necessary to correct all warnings from the `gofmt`. I hope that these changes will increase to 100% quality formatting. 

## Type of change

- [x] Code cleanup/refactoring

# How Has This Been Tested?
The result will be obtained after merge and refresh Go Report Card system. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MoonkiHong — APPROVED** [review]
This is a code cleanup. Verified. +1

**Review by t25kim — APPROVED** [review]
LGTM. Thnaks!

**Comment by MoonkiHong** [comment]
@suresh-lc PTAL.

**Review by suresh-lc — APPROVED** [review]
All the format changes are fine

**Pull request merged**
