### PR TITLE
[DO NOT MERGE] Use multi-stage builds and alpine3.12 image

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Trying to apply multi-stage builds for convenience.
It doesn't work properly under the following conditions.
* OS version : Ubuntu 18.04
* Architecture : Arm, Arm64
 
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Below is just an example and you can delete it when you contribute.

```
Example
1. Describe the reproduction procedures freely.
2. Or list up the test description like :
  - [ ] Unittest
  - [ ] Execution of Container
  - [ ] Execution on top of Native
  - [ ] Execution on top of Android
```

**Test Configuration**:
* Firmware version: (OS type and version, e.g., Ubuntu 14.04, etc.)
* Hardware: (e.g., x86-64, ARM, CPU type, RAM size, etc.)
* Toolchain: (e.g., Docker and Go versions)
* Edge Orchestration Release: (e.g., Alpha, Baobab, Coconut)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
@tdrozdovsky Any idea why the arm and arm64 architecture isn't built on Ubuntu 18.04?

**Comment by t25kim** [comment]
@tdrozdovsky I found that the qemu files should be in the proper place. Sorry for the inconvenience. I will update the code soon and request a review.

**Comment by tdrozdovsky** [comment]
> 
> 
> @tdrozdovsky I found that the qemu files should be in the proper place. Sorry for the inconvenience. I will update the code soon and request a review.

I was surprised that you deleted the qemu. Since without it, the build can be successful, but the format of the executive file and libraries will not work. Even conducted an experiment for Ubuntu 20.04 and yes binary does not work!

**Comment by tdrozdovsky** [comment]
And I also plan that we will have a folder with Dockerfiles (for different images). And in the configuration file, we will specify which file to connect. It will make flexible build system for our project

**Comment by t25kim** [comment]
@tdrozdovsky @MoonkiHong @suresh-lc Unfortunately it failed to build arm and arm64 binaries on Ubuntu 18.04 despite putting the qemu files in the /usr/bin/ folder. I think we can talk about HomeEdge's alpine image in this PR, so if you have any good ideas, please share them.

> And I also plan that we will have a folder with Dockerfiles (for different images). And in the configuration file, we will specify which file to connect. It will make flexible build system for our project

This is a very good idea. Let's do this together.

> I was surprised that you deleted the qemu. Since without it, the build can be successful, but the format of the executive file and libraries will not work. Even conducted an experiment for Ubuntu 20.04 and yes binary does not work!

I updated the PR and the binary built on my ubuntu 20.04 laptop worked properly on RPi. Could you test it again?

**Pull request closed without merging**
