### PR TITLE
Fix Native and Android Build Failure

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Native and Android build scripts are modified according to Go Modules.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. Install Android SDK and NDK ([Installation Guide](https://github.com/lf-edge/edge-home-orchestration-go/blob/77a6ff585d68f72077a30de601a3c2e0ec16b30b/doc/platforms/x86_64_linux/x86_64_android.md)) 
  **Tested by `ndk;21.3.6528147`, Do not use `ndk;22.0.7026061`.**
2. Run a command below.
$ ./build.sh object x86_64

### Result
```
-----------------------------------
 Build clean
-----------------------------------
GO111MODULE=on go clean
rm -rf /home/t25kim/work/edge-home-orchestration-go/vendor
rm -rf /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output
rm -rf /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output

-----------------------------------
 Go Mod Vendor
-----------------------------------
GO111MODULE=on go mod vendor


**********************************
 Target Binary arch is amd64
**********************************

----------------------------------------
 Create Static object of Orchestration
----------------------------------------
mkdir -p /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/inc/linux_x86-64 /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/lib/linux_x86-64
CGO_ENABLED=1 GO111MODULE=on go build -ldflags '-extldflags "-static" -X main.version= -X main.commitID=02e6da1 -X main.buildTime=20210127.1850 -X main.buildTags=' -o /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/lib/linux_x86-64/liborchestration.a -buildmode=c-archive /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi || exit 1
mv /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/lib/linux_x86-64/liborchestration.h /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/inc/linux_x86-64/orchestration.h
ls -al /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output/lib/linux_x86-64
total 37080
drwxrwxr-x 2 t25kim t25kim     4096  1월 27 18:50 .
drwxrwxr-x 3 t25kim t25kim     4096  1월 27 18:50 ..
-rw-rw-r-- 1 t25kim t25kim 37960302  1월 27 18:50 liborchestration.a

**********************************
 Target Binary is for Android
**********************************

-------------------------------------------
 Create Android archive from Java interface
-------------------------------------------
mkdir -p /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output
gomobile bind -ldflags '-X main.version= -X main.commitID=02e6da1 -X main.buildTime=20210127.1850 -X main.buildTags=' -o /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output/liborchestration.aar -target=android/amd64 -androidapi=23 /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi || exit 1
ls -al /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output
total 8388
drwxrwxr-x 2 t25kim t25kim    4096  1월 27 18:50 .
drwxrwxr-x 3 t25kim t25kim    4096  1월 27 18:50 ..
-rw-rw-r-- 1 t25kim t25kim 8566527  1월 27 18:50 liborchestration.aar
-rw-rw-r-- 1 t25kim t25kim   10432  1월 27 18:50 liborchestration-sources.jar


**********************************
 Edge-orchestration Archive
**********************************
tree /home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output
/home/t25kim/work/edge-home-orchestration-go/src/interfaces/capi/output
├── inc
│   └── linux_x86-64
│       └── orchestration.h
└── lib
    └── linux_x86-64
        └── liborchestration.a

4 directories, 2 files
tree /home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output
/home/t25kim/work/edge-home-orchestration-go/src/interfaces/javaapi/output
├── liborchestration.aar
└── liborchestration-sources.jar

0 directories, 2 files
```

**Test Configuration**:
* Firmware version: Ubuntu 18.04
* Hardware: x86-64
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tdrozdovsky** [comment]
I have tested successfully, but there are some notes:
1) you must specify which version to install. eg `./sdkmanager --install "ndk; 21.3.6528147"`
2) in the case when the build was unsuccessful (absence of Java or others) we have residual artifacts for example:
```
virtual-pc@virtualpc-VirtualBox:~/projects/edge-home-orchestration-go$ git status
## fix_build
 M go.mod
?? tmpvendor/
```
After discussion with the @t25kim, we decided to postpone until we correct these inaccuracies.
I want to note that the **@t25kim made a very important contribution!**
Thanks for your contribution!

**Comment by t25kim** [comment]
@MoonkiHong @suresh-lc @tdrozdovsky @mgjeong Please review the PR updated.

**Review by MoonkiHong — APPROVED** [review]
LGTM! Thank you for the delicate evaluation and improved/confirmed contribution! @t25kim and recommendation from @tdrozdovsky !

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Pull request merged**
