### PR TITLE
Use api, docs, examples and test folders by Standard Go Project Layout

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

This PR is intended to refactor folder structures by Standard Go Project Layout.

Related #209

## Type of change

- [x] Code cleanup/refactoring
- [x] Documentation update
- [x] This change requires a documentation update

# How Has This Been Tested?
No Code Change

**Test Configuration**:
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
This PR will be updated when #262 , #263 merged.

**Comment by t25kim** [comment]
Reopen with the update code.

**Review by tdrozdovsky — APPROVED** [review]
LGTM! Thanks to @t25kim for the work. If it turns out that some links are not working we can always fix it.

**Please note that after this commit, some links in CII Best Practices will not work!**
I'm asking you to accept this commit as soon as possible so I can check it out and make it correct.

**Review by MoonkiHong — APPROVED** [review]
LGTM.

**Pull request merged**
