### PR TITLE
Apply reactjs template

### PR DESCRIPTION
**Pull request by t25kim**
Signed-off-by: Taewan Kim <t25.kim@samsung.com>

# Description

Related #425 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
### Build React code
1. Install node.js and npm.
2. Go to `web` folder and install node modules with command `npm install`
3. Run the server with `npm start` and access the web page with `http://localhost:3000/`

### Edge Orchestration Container
1. Run `Edge Orchestration` with `WEBUI` environment variable like below.
```
docker run -it -d --privileged --network="host" --name edge-orchestration -e WEBUI=true -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro lfedge/edge-home-orchestration-go:latest
```
or 
```
make menuconfig
```
image```
```
make run 
```
2. Access the web page like `http://localhost:49153`

image

**Test Configuration**:
* OS type & version: Ubuntu 20.04
* Hardware: x86-64
* Edge Orchestration Release: v1.1.9

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tdrozdovsky — APPROVED** [review]
Great! Thank you

**Review by MoonkiHong — APPROVED** [review]
Thank you for this great initiation for the WebUI. Looks good to me. 😁

**Comment by tdrozdovsky** [comment]
@t25kim After executing commands to create a web page, the  `package-lock.json` file is updated and therefore `git` marks this file as changed
```
git stn
## pr/531
 M web/package-lock.json
```
This must be avoided. This can be done in two ways:
1) store the template of this  `package-lock.json` file and copy it to a `web` folder
2) execute command:
```
npm config set package-lock false
```

What do you think about this? Or do you have other solutions?

**Comment by t25kim** [comment]
@tdrozdovsky Thank you! This is a great advice.

> @t25kim After executing commands to create a web page, the `package-lock.json` file is updated and therefore `git` marks this file as changed
> 
> ```
> git stn
> ## pr/531
>  M web/package-lock.json
> ```
> 
> This must be avoided. This can be done in two ways:
> 
> 1. store the template of this  `package-lock.json` file and copy it to a `web` folder
> 2. execute command:
> 
> ```
> npm config set package-lock false
> ```
> 
> What do you think about this? Or do you have other solutions?

I would prefer not to track the file since  it is generated automatically with `npm install`.
What about removing `package-lock.json` and adding it on the `.gitignore`?

**Comment by tdrozdovsky** [comment]
> I would prefer not to track the file since it is generated automatically with `npm install`. What about removing `package-lock.json` and adding it on the `.gitignore`?

I agree!

**Review by suresh-lc — APPROVED** [review]
Thanks for the seed code for web ui support

**Pull request merged**
