### PR TITLE
Modify DataStorage.md file based on the contents of docker-compose.yml

### PR DESCRIPTION
**Pull request by Seunghui98**
Signed-off-by: Lee Seunghui <hithere1012@naver.com>

# Description
This PR is the contents of modified DataStorage.md file based on the creation of docker-compose.yml file. 

Related to #297

## Type of change

- [x] Documentation update

# How Has This Been Tested?
```
$ cd deployments/datastorage
$ docker-compose up -d
```

**Test Configuration**:
* Firmware version: Ubuntu 20.04
* Hardware: x86-64
* Toolchain: Docker 20.10.6 and Go 1.16.3
* Edge Orchestration Release: Coconut

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM. Thank you for your contribution!

**Review by MoonkiHong — APPROVED** [review]
Thank you for your clarification of the document. +1

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Review by suresh-lc — APPROVED** [review]
LGTM

**Pull request merged**
