### PR TITLE
Refactore the log message format

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

# Description

For the same output of messages in the log, refactoring format log was made.

## Type of change

- [x] Code cleanup/refactoring

# How Has This Been Tested?

```
docker run -it -d --privileged --network="host" --name edge-orchestration -e SECURE=true -e CLOUD_SYNC=true -e LOGLEVEL=Debug -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro  lfedge/edge-home-orchestration-go:latest
```

**Test Configuration**:
* OS type & version: Ubuntu 18.04
* Hardware: x86-64
* Toolchain: Docker v20.10 and Go v1.16
* Edge Orchestration Release: v1.1.4

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM Thanks!

**Comment by MoonkiHong** [comment]
@tdrozdovsky What about taking care of detected code smell (6 issues that is a duplicated literal instead of constant)?

**Comment by tdrozdovsky** [comment]
> @tdrozdovsky What about taking care of detected code smell (6 issues that is a duplicated literal instead of constant)?

Fixed. Thank you!

**Review by suresh-lc — APPROVED** [review]
Thanks for log message formatting. LGTM

**Review by MoonkiHong — APPROVED** [review]
Thank you for the contribution. It looks good to me. 😁

**Pull request merged**
