### PR TITLE
Folder Changes and MNEDC Config to YAML

### LINKED ISSUE #209: [Folder Structure] Follow standard Go project Layout
There is a popular [**standard** Go application project layout](https://github.com/golang-standards/project-layout) and many projects follow it.
I think we should change the folder structure in terms of this guide like below.
- `GoMain/src/main` > `cmd`
- `Buillder` > `build`
- `samples` > `examples`
- `samples/datastorage` > `configs/datastorage`
- `src` > `internal`
- `doc` > `docs`
- `doc/edge_orchestration_api.yaml` and `doc/edge_orchestration_api_secure.yaml` > `api/...`

Please add or rectify the list above since it might be incorrect!

### PR DESCRIPTION
**Pull request by sun-sharma**
Signed-off-by: Sunchit Sharma <sun.sharma@samsung.com>

# Description

1. "samples" Folder had been removed and 2 new folders : "configs" and "examples" have been created.
2. "datastorage" and "mnedc" configuration moved to configs and Native examples moved to examples
3. client.config ->client-config.yaml , corresponding code changes have been made 

Fixes #209 

## Type of change

Please delete options that are not relevant.

- [X] Code cleanup/refactoring
- [X] Documentation update

# How Has This Been Tested?

1. Set Up one system in Main NAT as MNEDC server
2. Set up 2 system in Sub NAT as MNEDC Client
3. Checked the logs for connection
4. Requested Service from Sub NAT system to Main NAT system
5. Worked Properly as expected.

**Test Configuration**:

- Firmware version: Ubuntu 16.04
- Hardware: x86-64
- Edge Orchestration Release: Coconut

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
Thank you for this contribution!
I recommend you to split the PR for ease of discussion and understanding like below.
1. Applying yaml to the MNEDC config file 
2. Changing folder structure

**Comment by MoonkiHong** [comment]
> Thank you for this contribution!
> I recommend you to split the PR for ease of discussion and understanding like below.
> 
> 1. Applying yaml to the MNEDC config file
> 2. Changing folder structure

@sun-sharma Please refer to [CONTRIBUTING](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/.github/CONTRIBUTING.md) session 11. We recommend that the PR would be good in a feature basis.

**Comment by sun-sharma** [comment]
Sure, I would do that. Thank you.

**Comment by sun-sharma** [comment]
I am closing this PR and splitting into two.

**Pull request closed without merging**
