### PR TITLE
[DataStorage] APIs to add Event and delete Events from database based on event ids

### PR DESCRIPTION
**Pull request by nitu-s-gupta**
Signed-off-by: Nitu Gupta <nitu.gupta@samsung.com>

# Description
Currently DataStorage has APIs to add data to the database or get the reading. API to delete a record from database is not present. This PR will add an API to delete record from CoreData given the Event ID

Usage Example
Add an Event
curl --location --request POST 'http://{DeviceServiceIP:Port}/api/v1/event'
Delete an Event
curl --location --request DELETE 'http://192.168.1.107:49986/api/v1/event/id/{EventID}"

Fixes # (issue)

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
1. Run the Docker container for Edge-orchestration 
```
docker run -it -d --privileged --network="host" --name edge-orchestration  -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro  lfedge/edge-home-orchestration-go:latest
```
2. Post an event by calling the API
curl --location --request POST 'http://192.168.1.107:49986/api/v1/event' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "device":"camera",
    "readings":[{
        "name":"cowcount",
        "value":"9"
    }]
}'
This will return an id of the event (In this example it returned 0d8d6738-5968-4b6c-92eb-1d45b2b3740a) 

3. Call the delete API using 
curl --location --request DELETE 'http://192.168.1.107:49986/api/v1/event/id/0d8d6738-5968-4b6c-92eb-1d45b2b3740a'

This will return true in case of success

**Test Configuration**:
* OS type & version: (Ubuntu 20.04)
* Hardware: (x86-64)
* Edge Orchestration Release: (v1.1.0)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM 
By the way, how to get the information inserted with add event API?

**Comment by nitu-s-gupta** [comment]
> LGTM By the way, how to get the information inserted with add event API?

information of what? Addevent will return the id of the event inserted

**Comment by t25kim** [comment]
> 2\. {
>     "device":"camera",
>     "readings":[{
>     "name":"cowcount",
>     "value":"9"
>     }]
>     }

Input from service application such as `{
"device":"camera",
"readings":[{
"name":"cowcount",
"value":"9"
}]
}`

**Comment by t25kim** [comment]
> > > > LGTM By the way, how to get the information inserted with add event API?
> > > 
> > > 
> > > information of what? Addevent will return the id of the event inserted
> > 
> > 
> > Input from service application such as `{ "device":"camera", "readings":[{ "name":"cowcount", "value":"9" }] }`
> 
> This information can be obtained from database using the reading API or by calling the api in coredatabase to get all the events

Can a service application fetch the information through DataStroage REST API at the moment?

**Comment by nitu-s-gupta** [comment]
> > > > > LGTM By the way, how to get the information inserted with add event API?
> > > > 
> > > > 
> > > > information of what? Addevent will return the id of the event inserted
> > > 
> > > 
> > > Input from service application such as `{ "device":"camera", "readings":[{ "name":"cowcount", "value":"9" }] }`
> > 
> > 
> > This information can be obtained from database using the reading API or by calling the api in coredatabase to get all the events
> 
> Can a service application fetch the information through DataStroage REST API at the moment?

Yes reading API

> > > > > LGTM By the way, how to get the information inserted with add event API?
> > > > 
> > > > 
> > > > information of what? Addevent will return the id of the event inserted
> > > 
> > > 
> > > Input from service application such as `{ "device":"camera", "readings":[{ "name":"cowcount", "value":"9" }] }`
> > 
> > 
> > This information can be obtained from database using the reading API or by calling the api in coredatabase to get all the events
> 
> Can a service application fetch the information through DataStroage REST API at the moment?

For readings fetching Service application can call /api/v1/device/{deviceNameKey}/resource/{resourceNameKey} Get API
For event fetching no API exits as provided by homeedge

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Review by MoonkiHong — APPROVED** [review]
Looks good to me.

**Pull request merged**
