### PR TITLE
Build orchestrator for container based on arm arch

### PR DESCRIPTION
**Pull request by tdrozdovsky**
# Description

Building an edge-orchestration container on a H/W board is a very complicated and inconvenient process. I added the ability to build the edge-orchestration container for different architectures on PC. Raspberry Pi 3 is an example.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

How to test is described in the `doc/platforms/raspberry_pi3/raspberry_pi3.md` file `#How to build` part.

```
Example
1. Describe the reproduction procedures freely.
2. Or list up the test description like :
  - [x] Unittest
  - [x] Execution of Container
  - [ ] Execution on top of Android
```

**Test Configuration**:
* Firmware version: Ubuntu 16.04
* Hardware: x86-64, ARM64
* Toolchain: (Docker and Go recommended versions
* Edge Orchestration Release: Baobab
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by t25kim** [comment]
@tdrozdovsky I think we don't need to make several Dockerfile files if we use an ARG variable like below.
```
ARG PLATFORM
FROM $PLATFORM/ubuntu:16.04
```

I revised some files for test such as Dockerfile, Makefile and build.sh.
Please refer to the build logs below. 

```
**********************************
 Create Docker container
**********************************
Error: No such container: edge-orchestration
Error: No such image: edge-orchestration:baobab
docker build --tag edge-orchestration:baobab --file /home/t25kim/workspace/edge-home-orchestration-go/GoMain/Dockerfile --build-arg PLATFORM=arm64v8 .
Sending build context to Docker daemon  143.5MB
Step 1/13 : ARG PLATFORM
Step 2/13 : FROM $PLATFORM/ubuntu:16.04
16.04: Pulling from arm64v8/ubuntu
f783735449ae: Pull complete
f35a03aa6fbe: Pull complete
f55e22189246: Pull complete
06a906902191: Pull complete
Digest: sha256:efe1dd034811acce9285ab90d22163797ad89997ea736a82da39b449d7981817
Status: Downloaded newer image for arm64v8/ubuntu:16.04
 ---> 6e092214ffcd
Step 3/13 : ENV TARGET_DIR=/edge-orchestration
 ---> Running in bcc9c9aab0fe
Removing intermediate container bcc9c9aab0fe
 ---> e999bbe9f135
Step 4/13 : ENV HTTP_PORT=56001
 ---> Running in d7b3bff0c0d9
Removing intermediate container d7b3bff0c0d9
 ---> dfaf2682915d
Step 5/13 : ENV MDNS_PORT=5353
 ---> Running in 49971e667d2d
Removing intermediate container 49971e667d2d
 ---> 847067538763
Step 6/13 : ENV ZEROCONF_PORT=42425
 ---> Running in 9df8371e9105
Removing intermediate container 9df8371e9105
 ---> cad0020a0989
Step 7/13 : ENV APP_MAIN_DIR=GoMain
 ---> Running in 70e24d6fe857
Removing intermediate container 70e24d6fe857
 ---> a27e76fe057c
Step 8/13 : ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
 ---> Running in bd367c3a9c24
Removing intermediate container bd367c3a9c24
 ---> 1022f398dd60
Step 9/13 : ENV APP_NAME=edge-orchestration
 ---> Running in fc0e8918e707
Removing intermediate container fc0e8918e707
 ---> 63566cdda7a5
Step 10/13 : COPY $APP_BIN_DIR/$APP_NAME $APP_MAIN_DIR/run.sh $TARGET_DIR/
 ---> bac33375246d
Step 11/13 : EXPOSE $HTTP_PORT $MDNS_PORT $ZEROCONF_PORT
 ---> Running in 29803d76bbcb
Removing intermediate container 29803d76bbcb
 ---> 97bbe209076f
Step 12/13 : WORKDIR $TARGET_DIR
 ---> Running in dcc60941b078
Removing intermediate container dcc60941b078
 ---> 4528125a09f5
Step 13/13 : CMD ["sh", "run.sh"]
 ---> Running in d7c2bec0046c
Removing intermediate container d7c2bec0046c
 ---> e87a9f4c4e9f
Successfully built e87a9f4c4e9f
Successfully tagged edge-orchestration:baobab
```

```
**********************************
 Create Docker container
**********************************
edge-orchestration
Untagged: edge-orchestration:baobab
Deleted: sha256:e87a9f4c4e9ff5020bb6e118cfb77dc24a8715422eef6c060acc736b6a864cd3
Deleted: sha256:4528125a09f5ada591e6c726f4a99adbb8ec465f143e1adc36fa4d441b27917c
Deleted: sha256:97bbe209076f7c04ea0e6e221cf7d0e386f24aa2b2b3d08b7c1078e66d21232b
Deleted: sha256:bac33375246d4f0177cb0e973000d03cad423ab4c3eb502832bf872207567ad7
Deleted: sha256:18584e9790ae9184ed1ec4c548ed2ad6e88c3ee0acfe1190dfc311c30d0761e3
Deleted: sha256:63566cdda7a571fd77aae9da7725f3f1f6998a07ee32adca24adcb00fea5f49c
Deleted: sha256:1022f398dd6048e33eefde4e6b9ff045d3d8c3b55d59f7c554d129214f54f708
Deleted: sha256:a27e76fe057c82c269618b90634f3742b8bf1300debe023c901fd8d691a68d24
Deleted: sha256:cad0020a0989861e63d206dc6879ea00e009a524b4ac9db18e452bef3334fdbf
Deleted: sha256:847067538763daad5a427c4463b3f8007e5425ca657b9ab2fa421c94e97c29b0
Deleted: sha256:dfaf2682915def43db733bef0e905676a1f5bf6979ad406cc4c1a8599b81163b
Deleted: sha256:e999bbe9f13560fa1f6315f2c611cc26398f94cfd3488a306239d8e73e1d4a60
docker build --tag edge-orchestration:baobab --file /home/t25kim/workspace/edge-home-orchestration-go/GoMain/Dockerfile --build-arg PLATFORM=amd64 .
Sending build context to Docker daemon  144.1MB
Step 1/13 : ARG PLATFORM
Step 2/13 : FROM $PLATFORM/ubuntu:16.04
16.04: Pulling from amd64/ubuntu
7b378fa0f908: Pull complete
4d77b1b29f2e: Pull complete
7c793be88bae: Pull complete
ecc05c8a19c0: Pull complete
Digest: sha256:cc4755a9f2f76ca73055da11f1bdc01d65ce79202a68b041c67c32770c71954b
Status: Downloaded newer image for amd64/ubuntu:16.04
 ---> fab5e942c505
Step 3/13 : ENV TARGET_DIR=/edge-orchestration
 ---> Running in 759b3ec78f85
Removing intermediate container 759b3ec78f85
 ---> 1d55d036393a
Step 4/13 : ENV HTTP_PORT=56001
 ---> Running in 4b3804b10823
Removing intermediate container 4b3804b10823
 ---> a3c5066eda78
Step 5/13 : ENV MDNS_PORT=5353
 ---> Running in 108f91d8e608
Removing intermediate container 108f91d8e608
 ---> db18ea94d69e
Step 6/13 : ENV ZEROCONF_PORT=42425
 ---> Running in fc082b9666db
Removing intermediate container fc082b9666db
 ---> 7541de3b474b
Step 7/13 : ENV APP_MAIN_DIR=GoMain
 ---> Running in ede2ff757f96
Removing intermediate container ede2ff757f96
 ---> 99afa1ec5f6e
Step 8/13 : ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
 ---> Running in b66b628334b4
Removing intermediate container b66b628334b4
 ---> 2d20db066b3b
Step 9/13 : ENV APP_NAME=edge-orchestration
 ---> Running in 2dd8080dc671
Removing intermediate container 2dd8080dc671
 ---> 0e99c33d31ca
Step 10/13 : COPY $APP_BIN_DIR/$APP_NAME $APP_MAIN_DIR/run.sh $TARGET_DIR/
 ---> b01fb44d3ea7
Step 11/13 : EXPOSE $HTTP_PORT $MDNS_PORT $ZEROCONF_PORT
 ---> Running in 92f5dbddb83e
Removing intermediate container 92f5dbddb83e
 ---> 3c84c58d9205
Step 12/13 : WORKDIR $TARGET_DIR
 ---> Running in 8575fa4e56e0
Removing intermediate container 8575fa4e56e0
 ---> 021cf1bd76e4
Step 13/13 : CMD ["sh", "run.sh"]
 ---> Running in 35aba7e69536
Removing intermediate container 35aba7e69536
 ---> 21f5637163f0
Successfully built 21f5637163f0
Successfully tagged edge-orchestration:baobab
```

**Comment by tdrozdovsky** [comment]
@t25kim I think this is a good idea, and I also thought about it. But then I thought that we might have different configurations of docker files for different architectures (and later different templates for one architecture) and as a result I decided that it was better to do it in this way. **Your opinion on this issue is very important to me.** Write me what you think about it. Since I like your solution too.

P.S. In general, I think that we will need to get away from the build script, and port the configuration for the Makefile. This will allow users more flexibility in creating their own configuration. This is the reason for creating separate templates (something similar to the configuration configs for Linux)

**Comment by t25kim** [comment]
@tdrozdovsky It makes sense. I prefer implementing source code when necessary and there is no differences in Dockerfile among platforms at this moment. So I thought we don't need to separate it.

> In general, I think that we will need to get away from the build script, and port the configuration for the Makefile. This will allow users more flexibility in creating their own configuration. This is the reason for creating separate templates (something similar to the configuration configs for Linux)

I like your idea to port the configuration to the Makefile. However I don't want to increase the complexity because of the vague needs for the future.

**Comment by tdrozdovsky** [comment]
@t25kim Done! I agree, at the moment there is no need to complicate what may be used in the future.

**Comment by MoonkiHong** [comment]
@tdrozdovsky I have no idea why the latest commit (https://github.com/lf-edge/edge-home-orchestration-go/pull/118/commits/d1c21e7cabbfc1569ccfbe5069c5bf806bef2186) includes your previous commit in this PR https://github.com/lf-edge/edge-home-orchestration-go/pull/118/commits/b36e06deaf555944423c439c48413fc29f0b3df7. This roleback is not a new thing and no meaning to put as a new commit. Please rectify your PR to exclude this role-back and apply the differentiating points to your PR. Thank you.

**Comment by tdrozdovsky** [comment]
@MoonkiHong Done! I had other thoughts, but I agree with you, it would be more correct.

**Pull request merged**
