### PR TITLE
Update version - v1.1.17

### PR DESCRIPTION
**Pull request by MoonkiHong**
Signed-off-by: MoonkiHong <moonki1.hong@samsung.com>

Update list
- Update dependencies (PR#606)
- [ScoringMgr] Amendment of scoring API (PR#615)
- Update golang ver. - v1.19 (PR#611)

### CODE REVIEW

**Review by t25kim — APPROVED** [review]
LGTM!

**Review by t25kim — CHANGES_REQUESTED** [review]
We need to check CI issues first.

**Review by tdrozdovsky — APPROVED** [review]
LGTM

**Comment by MoonkiHong** [comment]
Still failed. Any reason for this?

**Review by t25kim — APPROVED** [review]

**Pull request merged**
